### PR TITLE
Prototyping direct messages

### PR DESCRIPTION
**Pull request by nkzarrabi**
Just checking if this is along the lines of what you had in mind. The tests aren't necessary. I think I would like to see the execution on a browser to really understand what I'm doing but as of now I'm simply creating connection on the back end.

Is there an issue open for creating/enhancing the connection front end so a user can actually see who they submit a request to?

### CODE REVIEW

**Comment by kerkeslager** [comment]
It's sort of what I had in mind. A few notes:

1. Let's borrow from existing messaging systems. We want essentially two views: one that lists all conversations, and one that lists all the messages in a conversation. `Conversation` isn't a model, and it probably shouldn't be, because the conversation is just a list of messages associated with the current user and a connected user. The create message form can be on the same view as the previous messages in the conversation, and we probably don't need update/delete views at the moment--once it's sent, it's sent.
2. I'm seeing that the way you've queried the connections is querying as if the current user might be on either side of the connection. Instead, try querying `request.user.connections` (I think?) which will return all the connections owned by the user in a performant way. Each of these connections will have a `self.opposite` which is the same connection, but owned by the opposite user so that they can query their connections efficiently. Creating a connection automatically creates its opposite, so these are a one-to-one model, but a user should generally only operate on their own connections. The only reason we'd get the opposite is to get all the messages associated with each connection.
3. The models I wrote aren't 100% great here, so feel free to change them. Particularly, I don't think we need `from_user`; we need a way to clarify that the owner of the `Connection` is the sender of the message, perhaps?

This is a fairly complicated feature, maybe this should wait until we can pair program on it.

**Comment by nkzarrabi** [comment]
That's fair. For the time being, I made some UML diagrams of core/models. 
That way I can take a closer look at the current system and see how I should go about changing them. 
```mermaid
classDiagram
    class User {
        +UUIDField id
        +CharField name
        display_name() : String
        feed() : Post[]
        is_connected_with(User) : Boolean
        connected_users() : User[]
        conversations() : Connection[]
    }
    class Connection {
        +UUIDField id
        +DateTimeField created_utc
        +ForeignKey opposite
        +ForeignKey owner
        +ForeignKey other_user
        messages() : Message[]
    }
    class Message {
        +UUIDField id
        +ForeignKey connection
        +DateTimeField created_utc
        +BooleanField read
        +CharField text
    }
    class Circle {
        +UUIDField id
        +CharField name
        +CharField color
        +ForeignKey owner
        members() : User[]
    }
    class Invitation {
        +UUIDField id
        +ForeignKey owner
        +CharField name
        +CharField message
        +ManyToManyField circles
    }
    class Post {
        +UUIDField id
        +DateTimeField created_utc
        +ForeignKey owner
        +CharField text
        +ManyToManyField circles
        publish(Circle[]) : void
    }
    class PostCircle {
        +UUIDField id
        +ForeignKey circle
        +ForeignKey post
    }
    class CircleMembership {
        +UUIDField id
        +ForeignKey circle
        +ForeignKey connection
    }
    class PostUser {
        +ForeignKey post_circle
        +ForeignKey circle_membership
    }

    User "1" -- "*" Circle : owns
    User "1" -- "*" Connection : owns
    User "1" -- "*" Invitation : owns
    User "1" -- "*" Message : sends
    User "1" -- "*" Post : creates

    Circle "1" -- "*" User : includes
    Circle "1" -- "*" PostCircle : associated_with
    Circle "1" -- "*" CircleMembership : consists_of

    Connection "2" -- "2" Connection : opposite
    Connection "*" -- "*" Message : contains

    Invitation "*" -- "*" Circle : targets
    Invitation "*" -- "*" User : invites

    Post "*" -- "*" PostCircle : grouped_into
    Post "*" -- "*" Circle : shared_with

    CircleMembership "*" -- "*" Connection : linked_to

    PostCircle "*" -- "1" Post : part_of
    PostCircle "*" -- "1" Circle : part_of

    PostUser "*" -- "1" PostCircle : connected_to
    PostUser "*" -- "1" CircleMembership : connected_to


```

**Comment by kerkeslager** [comment]
One thing to be aware of is that part of the complexity of this data model comes from the fact that I'm using foreign key cascading deletes to be sure that security is maintained, i.e. if a user disconnects from another user or deletes their user account, all their shared posts/messages will be deleted. As a result, some things that don't strictly need to be foreign keys (i.e. connections and messages) are foreign keyed against each other.

Re: Connections, you'll note that user.connections returns a list of connections where user is the owner of all the connections. If user is connected with other_user, other_user.connections contains a *separate* connection object which has user as the `other_user` in its fields. These connections are linked (via `opposite`) so that they come into existence and are deleted together. But queries are simplified because you don't have to check both sides of a `Connection` object to find all of a user's connections: all the information you need is in the `connections` queryset.

**Comment by kerkeslager** [comment]
I fleshed out the message models in [this PR](https://github.com/kerkeslager/friendzone/pull/34/files) which I'll merge soon, this should clarify my thinking on messages I think.

**Pull request closed without merging**
